#behat.yml
default:
  paths:
    features:  ../features
    bootstrap: ../features/bootstrap/
  extensions:
    Behat\MinkExtension\Extension:
      base_url: http://en.wikipedia.org
      goutte: ~
      selenium2: ~
